# Where things are
auto: true
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
collections: null


# Handling Reading
safe: false
exclude: ["README.md", ".git", ".idea"]
encoding : utf-8
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"


# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false


# Plugins
whitelist: []
gems:
    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap


# Conversion
markdown:    rdiscount
highlighter: pygments
pygments: true
lsi: true
excerpt_separator: "\n\n"


# Serving
detach:  false
port:    80
host:    http://cherrylee.name
baseurl: "/" # does not include hostname
url: http://cherrylee.name


# Outputting
paginate_path: page:num
paginate: 10
prelinkpath : ""
production_url : http://cherrylee.name
timezone:      null
quiet:    false
defaults: []

# site info
author : "cherrylee"
title: Cherry Lee Blog
description : 这是Cherry Lee的博客。
