# Handling Reading
safe: false
exclude: ["README.md", ".git", ".idea"]
encoding : utf-8
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"


# Serving
detach:  false
port:    80
host:    http://cherrylee.name
baseurl: "/" # does not include hostname
url: http://cherrylee.name


# site info
author : "cherrylee"
title: Cherry Lee Blog
description : 这是Cherry Lee的博客。
